/*

 *
 * Task code generated by SAS Studio 3.5 
 *
 * Generated on '2016-10-27, 1:09 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-573.26.1.el6.x86_64' 
 * Generated on SAS version '9.04.01M3P06242015' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50' 
 * Generated on web client 'http://localhost:10080/SASStudio/35/main?locale=en_CA&zone=GMT-04%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc reg data=WORK.N1LPGA2008 alpha=0.05 plots(label)=(diagnostics(unpack) 
		residuals rstudentbypredicted observedbypredicted);
	model Winnings=Rounds /*AvgDrive*/ /*Fairways*/ /*FwHits*/ /*FwHitsPct*/ /*FwMiss*/ /*FwMissPct*/ 
		GreenReg /*Putts*/ AvgPutts /*SandTraps*/ /*SandFwyPct*/ /*SandSaves*/ /*SandSavePct*/ /*LogWin*/ / 
		influence r collin vif tol stb;
	run;
quit;