/*
 *
 * Task code generated by SAS Studio 3.5 
 *
 * Generated on '9/29/16, 3:38 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-573.26.1.el6.x86_64' 
 * Generated on SAS version '9.04.01M3P06242015' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50' 
 * Generated on web client 'http://localhost:10080/SASStudio/35/main?locale=en_US&zone=GMT-04%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F35%2Findex=' 
 *
 */

proc sort data=SASHELP.BWEIGHT out=WORK.SORTTempTableSorted;
	by Married MomSmoke Boy;
run;

proc surveyselect data=WORK.SORTTempTableSorted out=WORK.RandomSample 
		method=srs samprate=0.2 seed=118897164;
	strata Married MomSmoke Boy / alloc=prop;
run;

proc delete data=WORK.SORTTempTableSorted;
run;